### ISSUE TITLE
two kinds of flex containers

### ISSUE THREAD

**Issue by luminecs** [luminecs/css-draft#1]
* [initial style files](https://github.com/luminecs/web-draft/issues/2#issue-2582409184)
* create directory `flexbox`.
* create file `two-kinds-of-flex-containers.html` in `flexbox` directory.
* write a proper title, like `Two kinds of flex containers`.
* copy the following code, and paste it into `<body>`:
```html
<article>
  <div>
    <div>
      Here is some content.
    </div>
    <div>
      More content than before, but no properties explicitly set.
    </div>
    <div>
      Lots and lots of content. Even more content than to the left, but no properties explicitly set.
    </div>
  </div>
  <p><code>display: flex; ⤴</code></p>
</article>

<article>
  <div>
    <div>
      Here is some content.
    </div>
    <div>
      More content than before, but no properties explicitly set.
    </div>
    <div>
      Lots and lots of content. Even more content than to the left, but no properties explicitly set.
    </div>
  </div>
  <p><code>display: inline-flex;</code> ⤴</p>
</article>

<article>
  <div>
    <div>flex item with<br/>
      two longer lines</div>
    <div>flex item</div>
    <div>flex item</div>
  </div>
  <p><code>display: flex;</code> ⤴</p>
</article>

<article>
  <div>
    <div>flex item with<br/>
      two longer lines</div>
    <div>flex item</div>
    <div>flex item</div>
  </div>
  <p><code>display: inline-flex;</code> ⤴</p>
</article>
```

* add base styles
```html
<style contenteditable>
  /* base styles */
  @import url(../styles/style-edit.css);
  style,
  body {
    font-family: "ubuntu mono", Consolas, monospace;
  }
  div > div {
    font-family: "Myriad Pro", Myriad, "Liberation Sans", "Nimbus Sans L", "Helvetica Neue", sans-serif;
  }
</style>
```

* set flex in div
* edit custom styles

```css
body {
  font-size: 20px;
  padding: 10px;
}
```

```css
p {
  margin-top: 0;
}
```

```css
div {
  background-color: rgba(0, 0, 0, 0.1);
}
```

```css
article > div {
  border: 1px dashed;
  padding: 3px;
}
```

```css
div > div {
  border: 1px solid;
  margin: 10px;
  padding: 20px 5px;
  line-height: 30px;
}
```
